### ISSUE TITLE
ERROR: Loading "scrapy_impersonate.ImpersonateDownloadHandler" for scheme "http"

### ISSUE THREAD

**Issue by notsocold** [jxlil/scrapy-impersonate#20]
When the crawler starts running，the following error occurred. verson 1.4.0
```
2024-08-14 11:07:11 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy_impersonate.ImpersonateDownloadHandler" for scheme "http"
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 55, in _load_handler
    dhcls = load_object(path)
  File "D:\Python\Python38\lib\site-packages\scrapy\utils\misc.py", line 79, in load_object
    mod = import_module(module)
  File "D:\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\__init__.py", line 1, in <module>
    from scrapy_impersonate.handler import ImpersonateDownloadHandler
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\handler.py", line 13, in <module>
    from scrapy_impersonate.parser import CurlOptionsParser, RequestParser
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\parser.py", line 7, in <module>
    class CurlOptionsParser:
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\parser.py", line 18, in CurlOptionsParser
    def _set_proxy_auth(self):
TypeError: 'staticmethod' object is not callable
2024-08-14 11:07:11 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy_impersonate.ImpersonateDownloadHandler" for scheme "https"
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 55, in _load_handler
    dhcls = load_object(path)
  File "D:\Python\Python38\lib\site-packages\scrapy\utils\misc.py", line 79, in load_object
    mod = import_module(module)
  File "D:\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\__init__.py", line 1, in <module>
    from scrapy_impersonate.handler import ImpersonateDownloadHandler
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\handler.py", line 13, in <module>
    from scrapy_impersonate.parser import CurlOptionsParser, RequestParser
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\parser.py", line 7, in <module>
    class CurlOptionsParser:
  File "D:\Python\Python38\lib\site-packages\scrapy_impersonate\parser.py", line 18, in CurlOptionsParser
    def _set_proxy_auth(self):
TypeError: 'staticmethod' object is not callable
```

**Comment by jxlil** [comment]
Hi @notsocold,

Thanks. This is already resolved in version 1.4.1
